version: '2.16'
services:
  dev:
    image: spotify-radio
    build: .
    environment:
      PORT: 3333
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules
    ports:
      - 3333:3333

  test:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-watch:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

  test-coverage:
    image: spotify-radio
    build: .
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/spotify-radio
      - node_modules:/spotify-radio/node_modules

volumes:
  node_modules: {}
